version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src/
    ports:
      - "8000:8000"
    env_file:
      - env/backend.env
      - env/postgres.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - db_data:/var/lib/postgresql/data
    platform: linux/amd64
    env_file:
      - env/postgres.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db_data:
