"""unique index added to user_saved_books

Revision ID: 17c04881a0dd
Revises: fb721372a2ba
Create Date: 2023-11-06 11:46:31.910066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c04881a0dd'
down_revision: Union[str, None] = 'fb721372a2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_saved_books', 'user_saved_books', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_saved_books', 'user_saved_books', type_='unique')
    # ### end Alembic commands ###
